version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_saas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: saasdb
      MYSQL_USER: saasuser
      MYSQL_PASSWORD: saaspass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
