import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { initDB } from "@/lib/initDB";
import TenantContextProvider from "@/app/contexts/TenantContext";
import AdminHeader from "@/app/components/AdminHeader/page";
import Header from "@/app/components/Header/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await initDB(); // ensure DB is initialized

  // Read tenant slug from request headers (set by middleware)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TenantContextProvider>
          {/* flex-col if user not logged in */}
          <div className="relative flex flex-col min-h-screen bg-(--light) dark:bg-(--dark) text-(--dark) dark:text-(--light)">
            {/* <AdminHeader /> */}
            {/* <Header /> */}
            {children}
          </div>
        </TenantContextProvider>
      </body>
    </html>
  );
}
